use customer_behavior;

select * from customerss limit 20;

-- 1. what is the total revenue generated by male vs. female customers?
select gender , sum(purchase_amount) as revenue 
from customerss
group by gender;

-- 2. which customers used a discount but still spent more than the average purchase amount?
select customer_id , purchase_amount 
from customerss 
where discount_applied = "yes" and purchase_amount >= (select avg(purchase_amount) from customerss);

-- 3. Which are the top 5 products with the highest average review rating?

select item_purchased , round(avg(review_rating),2) as "Average Product Rating"
from customerss 
group by item_purchased 
order by avg(review_rating) desc 
limit 5;

-- 4. Compare the Average purchase Amounts between standard and express shiping.

select shipping_type,round(avg(purchase_amount),2) as Average_purchase_Amounts
from customerss
where shipping_type in ("Standard","Express")
group by shipping_type;

-- 5. Do Subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,
count(customer_id) as Total_Customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customerss
group by subscription_status
order by total_revenue , avg_spend desc;

-- 6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased ,
round(100*sum(case when discount_applied = "yes" then 1 else 0 end)/count(*),2) as discount_rate
from customerss 
group by item_purchased
order by discount_rate desc
limit 5;

-- 7. Segment customers into new ,returning , and loyal based on their total
-- number of privious-purchases , and show the count of each segment 

with customer_type as (
select customer_id , previous_purchases,
case 
	when previous_purchases = 1 then "New"
    when previous_purchases between 2 and 10 then "Returning"
    else "Loyal"
    end as customer_segment
from customerss     
)

select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- 8. what are the top 3 most purcahsed products with in each category

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customerss
group by category , item_purchased
)

select item_rank , category , item_purchased , total_orders
from item_counts
where item_rank <=3; 

-- 9. Are customers who are repeate buyers (more than 5 privious purchases) also likely to subscribe ?

select subscription_status,
count(customer_id) as repeat_buyers 
from customerss
where previous_purchases > 5 
group by subscription_status
order by repeat_buyers desc;

-- 10.What is revenue contribution by the age group ?

select age_group,
sum(purchase_amount) as total_revenue
from customerss
group by age_group
order by total_revenue desc;









